name: text
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  get: ^3.22.2
  r_dart_library:
    git:
      url: https://github.com/YK-Unit/r_dart_library.git
      ref: 0.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - packages/text/assets/images/bubbles.jpg
    - packages/text/assets/images/logo.png
    - packages/text/assets/images/whater.jpg
flr:
  core_version: 3.1.0
  dartfmt_line_length: 80
  assets:
    - lib/assets/images
    - lib/assets/texts
  fonts: []
